version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ".:/app"
      - "app-build:/app/_build"
      - "app-deps:/app/deps"
    links:
      - "db:database"
    depends_on:
      - db

  db:
    image: postgis/postgis:12-3.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventstore
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg-data:
  app-build:
  app-deps:
